theme: jekyll-theme-midnight
title: "Team Turtle's Top Ten"
description: "Haseeb, Nathan, Sabine, and Alyssa showcase their abilities involving SASS/HTML and CPT"
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "January 6, 2023"
google_analytics:
